/**
 * Control Hub - Permissions System
 * نظام الصلاحيات - مركز التحكم
 * نادي سباقات الخيل (JCSA)
 * 
 * This file defines all permissions for each role
 * هذا الملف يحدد جميع الصلاحيات لكل دور
 */

import { USER_ROLES, USER_PORTALS } from './constants';

// ==================== Permission Actions - أنواع العمليات ====================
// view=عرض, create=إنشاء, update=تعديل, delete=حذف نهائي, approve=اعتماد,
// export=تصدير, manage=إدارة الإعدادات وتعيين المسؤولين والتحكم الكامل,
// archive=أرشفة/حذف ناعم (إخفاء بدون حذف فعلي)
export const ACTIONS = {
  VIEW: 'view',
  CREATE: 'create',
  UPDATE: 'update',
  DELETE: 'delete',
  APPROVE: 'approve',
  EXPORT: 'export',
  MANAGE: 'manage',
  ARCHIVE: 'archive',
} as const;

export type Action = typeof ACTIONS[keyof typeof ACTIONS];

// ==================== Resources - الموارد ====================
export const RESOURCES = {
  // Admin Resources
  USERS: 'users',
  AUDIT_LOGS: 'audit_logs',
  SESSIONS: 'sessions',
  SYSTEM_SETTINGS: 'system_settings',
  BUSINESS_DEPARTMENTS: 'business_departments',
  SYSTEMS_STATUS: 'systems_status',
  
  // IT Director Resources
  IT_PROJECTS: 'it_projects',
  IT_TICKETS: 'it_tickets',
  IT_ESCALATIONS: 'it_escalations',
  IT_ASSETS: 'it_assets',
  IT_KPIS: 'it_kpis',
  IT_TEAMS: 'it_teams',
  IT_VENDORS: 'it_vendors',
  EXTERNAL_SYSTEMS: 'external_systems',
  SYSTEM_APPROVALS: 'system_approvals',
  IT_REFERRALS: 'it_referrals',
  
  // Infrastructure Resources
  INFRASTRUCTURE_SERVERS: 'infrastructure_servers',
  INFRASTRUCTURE_NETWORK: 'infrastructure_network',
  INFRASTRUCTURE_STORAGE: 'infrastructure_storage',
  INFRASTRUCTURE_MONITORING: 'infrastructure_monitoring',
  INFRASTRUCTURE_TASKS: 'infrastructure_tasks',
  INFRASTRUCTURE_PROJECTS: 'infrastructure_projects',
  INFRASTRUCTURE_ASSETS: 'infrastructure_assets',
  INFRASTRUCTURE_SLA: 'infrastructure_sla',
  
  // Cybersecurity Resources
  SECURITY_INCIDENTS: 'security_incidents',
  SECURITY_VULNERABILITIES: 'security_vulnerabilities',
  SECURITY_THREATS: 'security_threats',
  SECURITY_RISKS: 'security_risks',
  CYBERSECURITY_ASSETS: 'cybersecurity_assets',
  CYBERSECURITY_SLA: 'cybersecurity_sla',
  
  // Digital Transformation Resources
  DIGITAL_INITIATIVES: 'digital_initiatives',
  DIGITAL_APPLICATIONS: 'digital_applications',
  CLOUD_SERVICES: 'cloud_services',
  DIGITAL_CLOUD: 'digital_cloud',
  DIGITAL_ASSETS: 'digital_assets',
  DIGITAL_SLA: 'digital_sla',
  
  // Support Resources
  SUPPORT_TICKETS: 'support_tickets',
  SUPPORT_ASSETS: 'support_assets',
  SUPPORT_SLA: 'support_sla',
  
  // DMO Resources
  DATA_CATALOG: 'data_catalog',
  DATA_ASSETS: 'data_assets',
  DATA_FLOWS: 'data_flows',
  DATA_AGREEMENTS: 'data_agreements',
  DATABASE_CONNECTIONS: 'database_connections',
  DMO_REQUESTS: 'dmo_requests',
  DMO_DOCUMENTS: 'dmo_documents',
  
  // Committee Resources
  COMMITTEE_DECISIONS: 'committee_decisions',
  COMMITTEE_MEETINGS: 'committee_meetings',
  COMMITTEE_VOTING: 'committee_voting',
  COMMITTEE_MEMBERS: 'committee_members',
  COMMITTEE_MINUTES: 'committee_minutes',
  COMMITTEE_TASKS: 'committee_tasks',
  COMMITTEE_SETTINGS: 'committee_settings',
  
  // Common Resources
  SLA_AGREEMENTS: 'sla_agreements',
  KNOWLEDGE_BASE: 'knowledge_base',
  DOCUMENTS: 'documents',
  DEPARTMENT_ASSETS: 'department_assets',
  NOTIFICATIONS: 'notifications',
  DASHBOARD: 'dashboard',
  
  // Compliance Resources - موارد الامتثال
  COMPLIANCE: 'compliance',
  PDPL_CONSENTS: 'pdpl_consents',
  PDPL_BREACHES: 'pdpl_breaches',
  PDPL_ROPA: 'pdpl_ropa',
  NDMO_ASSESSMENTS: 'ndmo_assessments',
  DATA_CLASSIFICATIONS: 'data_classifications',
  PRIVACY_NOTICES: 'privacy_notices',
} as const;

export type Resource = typeof RESOURCES[keyof typeof RESOURCES];

// ==================== Permission Type ====================
export interface Permission {
  resource: Resource;
  actions: Action[];
}

// ==================== Role Permissions Matrix ====================
// مصفوفة الصلاحيات لكل دور

export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  // ==================== System Admin - مدير النظام ====================
  // دور تقني بحت: إدارة النظام والمستخدمين — الاعتماد التشغيلي يخص IT Director
  [USER_ROLES.SYSTEM_ADMIN]: [
    { resource: RESOURCES.USERS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.AUDIT_LOGS, actions: [ACTIONS.VIEW, ACTIONS.EXPORT] },
    { resource: RESOURCES.SESSIONS, actions: [ACTIONS.VIEW, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.SYSTEM_SETTINGS, actions: [ACTIONS.VIEW, ACTIONS.UPDATE, ACTIONS.MANAGE] },
    { resource: RESOURCES.BUSINESS_DEPARTMENTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE] },
    { resource: RESOURCES.SYSTEMS_STATUS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.DASHBOARD, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.NOTIFICATIONS, actions: [ACTIONS.VIEW, ACTIONS.UPDATE] },
    { resource: RESOURCES.DOCUMENTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.DMO_DOCUMENTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.IT_TICKETS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE] },
    { resource: RESOURCES.IT_PROJECTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE] },
    { resource: RESOURCES.IT_ASSETS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE] },
    { resource: RESOURCES.COMPLIANCE, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.PDPL_CONSENTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.PDPL_BREACHES, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.PDPL_ROPA, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.NDMO_ASSESSMENTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.APPROVE, ACTIONS.MANAGE] },
    { resource: RESOURCES.DATA_CLASSIFICATIONS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.APPROVE, ACTIONS.MANAGE] },
    { resource: RESOURCES.PRIVACY_NOTICES, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.APPROVE, ACTIONS.MANAGE] },
    // FIX #13: الأنظمة الخارجية مركزية — فقط admin و director يتحكمان
    { resource: RESOURCES.EXTERNAL_SYSTEMS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.APPROVE, ACTIONS.MANAGE] },
    { resource: RESOURCES.SYSTEM_APPROVALS, actions: [ACTIONS.VIEW, ACTIONS.APPROVE, ACTIONS.MANAGE] },
    { resource: RESOURCES.IT_ESCALATIONS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.APPROVE, ACTIONS.MANAGE] },
    { resource: RESOURCES.IT_KPIS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.IT_TEAMS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.IT_VENDORS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.SLA_AGREEMENTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.IT_REFERRALS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.MANAGE] },
    { resource: RESOURCES.KNOWLEDGE_BASE, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.DEPARTMENT_ASSETS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.SECURITY_INCIDENTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.SECURITY_VULNERABILITIES, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.SECURITY_THREATS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.SECURITY_RISKS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.CYBERSECURITY_ASSETS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.DATA_CATALOG, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.DATA_AGREEMENTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.DATA_ASSETS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.DATA_FLOWS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.DATABASE_CONNECTIONS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.DMO_REQUESTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.APPROVE, ACTIONS.MANAGE] },
    { resource: RESOURCES.INFRASTRUCTURE_SERVERS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.INFRASTRUCTURE_NETWORK, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.INFRASTRUCTURE_STORAGE, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.INFRASTRUCTURE_MONITORING, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.DIGITAL_INITIATIVES, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.DIGITAL_APPLICATIONS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.CLOUD_SERVICES, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.DIGITAL_ASSETS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    // FIX #5: القرارات لا تُحذف — تُلغى بقرار جديد (أزيل DELETE)
    { resource: RESOURCES.COMMITTEE_DECISIONS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.APPROVE, ACTIONS.MANAGE] },
    { resource: RESOURCES.COMMITTEE_MEETINGS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.COMMITTEE_MEMBERS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.COMMITTEE_VOTING, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.COMMITTEE_MINUTES, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.COMMITTEE_TASKS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.COMMITTEE_SETTINGS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.SUPPORT_TICKETS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.SUPPORT_ASSETS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
  ],

  // ==================== IT Director General - المدير العام لتقنية المعلومات ====================
  // FIX #7: مستندات DMO عرض فقط (ملكية DMO) | FIX #13: الأنظمة الخارجية تحكم كامل (مركزي)
  [USER_ROLES.IT_DIRECTOR]: [
    { resource: RESOURCES.IT_PROJECTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.APPROVE] },
    { resource: RESOURCES.IT_TICKETS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE] },
    { resource: RESOURCES.IT_ESCALATIONS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE] },
    { resource: RESOURCES.IT_ASSETS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE] },
    { resource: RESOURCES.IT_KPIS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE] },
    { resource: RESOURCES.IT_TEAMS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.IT_VENDORS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE] },
    { resource: RESOURCES.EXTERNAL_SYSTEMS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.APPROVE] },
    { resource: RESOURCES.SYSTEM_APPROVALS, actions: [ACTIONS.VIEW, ACTIONS.APPROVE] },
    { resource: RESOURCES.IT_REFERRALS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.APPROVE] },
    { resource: RESOURCES.AUDIT_LOGS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.DASHBOARD, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.NOTIFICATIONS, actions: [ACTIONS.VIEW, ACTIONS.UPDATE] },
    { resource: RESOURCES.INFRASTRUCTURE_SERVERS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.INFRASTRUCTURE_NETWORK, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.SECURITY_INCIDENTS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.DIGITAL_INITIATIVES, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.SUPPORT_TICKETS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.DATA_CATALOG, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.KNOWLEDGE_BASE, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE] },
    { resource: RESOURCES.DMO_DOCUMENTS, actions: [ACTIONS.VIEW] },
  ],

  // ==================== Infrastructure Manager - مدير إدارة البنية التحتية ====================
  // FIX #2: كتالوج البيانات عرض فقط (ملكية DMO) | FIX #13: الأنظمة الخارجية عرض فقط (مركزية)
  [USER_ROLES.IT_INFRASTRUCTURE_MANAGER]: [
    { resource: RESOURCES.INFRASTRUCTURE_SERVERS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.INFRASTRUCTURE_NETWORK, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.INFRASTRUCTURE_STORAGE, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.INFRASTRUCTURE_MONITORING, actions: [ACTIONS.VIEW, ACTIONS.MANAGE] },
    { resource: RESOURCES.INFRASTRUCTURE_TASKS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.APPROVE] },
    { resource: RESOURCES.INFRASTRUCTURE_PROJECTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.APPROVE] },
    { resource: RESOURCES.INFRASTRUCTURE_ASSETS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.DEPARTMENT_ASSETS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE] },
    { resource: RESOURCES.EXTERNAL_SYSTEMS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.SLA_AGREEMENTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE] },
    { resource: RESOURCES.KNOWLEDGE_BASE, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE] },
    { resource: RESOURCES.DOCUMENTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE] },
    { resource: RESOURCES.DATA_CATALOG, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.DATABASE_CONNECTIONS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.DASHBOARD, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.NOTIFICATIONS, actions: [ACTIONS.VIEW, ACTIONS.UPDATE] },
  ],

  // ==================== Infrastructure Staff - موظف البنية التحتية ====================
  // FIX #10: أزيل DELETE على السيرفرات/الشبكات/التخزين (فقط المدير يحذف)
  // FIX #2: كتالوج البيانات عرض فقط | FIX #13: الأنظمة الخارجية عرض فقط
  [USER_ROLES.IT_INFRASTRUCTURE_STAFF]: [
    { resource: RESOURCES.INFRASTRUCTURE_SERVERS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.ARCHIVE] },
    { resource: RESOURCES.INFRASTRUCTURE_NETWORK, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.ARCHIVE] },
    { resource: RESOURCES.INFRASTRUCTURE_STORAGE, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.ARCHIVE] },
    { resource: RESOURCES.INFRASTRUCTURE_MONITORING, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.INFRASTRUCTURE_TASKS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.ARCHIVE] },
    { resource: RESOURCES.INFRASTRUCTURE_PROJECTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE] },
    { resource: RESOURCES.INFRASTRUCTURE_ASSETS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.ARCHIVE] },
    { resource: RESOURCES.DEPARTMENT_ASSETS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE] },
    { resource: RESOURCES.EXTERNAL_SYSTEMS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.SLA_AGREEMENTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE] },
    { resource: RESOURCES.KNOWLEDGE_BASE, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE] },
    { resource: RESOURCES.DOCUMENTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE] },
    { resource: RESOURCES.DATA_CATALOG, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.DATABASE_CONNECTIONS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.DASHBOARD, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.NOTIFICATIONS, actions: [ACTIONS.VIEW, ACTIONS.UPDATE] },
  ],

  // ==================== Cybersecurity Manager - مدير إدارة الأمن السيبراني ====================
  // FIX #2: كتالوج البيانات عرض فقط | FIX #13: الأنظمة الخارجية عرض فقط
  [USER_ROLES.IT_CYBERSECURITY_MANAGER]: [
    { resource: RESOURCES.SECURITY_INCIDENTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.ARCHIVE, ACTIONS.MANAGE] },
    { resource: RESOURCES.SECURITY_VULNERABILITIES, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.ARCHIVE, ACTIONS.MANAGE] },
    { resource: RESOURCES.SECURITY_THREATS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.ARCHIVE, ACTIONS.MANAGE] },
    { resource: RESOURCES.SECURITY_RISKS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.APPROVE] },
    { resource: RESOURCES.CYBERSECURITY_ASSETS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.DEPARTMENT_ASSETS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE] },
    { resource: RESOURCES.EXTERNAL_SYSTEMS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.SLA_AGREEMENTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE] },
    { resource: RESOURCES.KNOWLEDGE_BASE, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE] },
    { resource: RESOURCES.DOCUMENTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE] },
    { resource: RESOURCES.DATA_CATALOG, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.DATABASE_CONNECTIONS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.DASHBOARD, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.NOTIFICATIONS, actions: [ACTIONS.VIEW, ACTIONS.UPDATE] },
  ],

  // ==================== Cybersecurity Staff - موظف الأمن السيبراني ====================
  // FIX #4: أزيل DELETE على الحوادث/الثغرات/التهديدات (سجلات أمنية لا تُحذف — archive فقط)
  // FIX #2: كتالوج البيانات عرض فقط | FIX #13: الأنظمة الخارجية عرض فقط
  [USER_ROLES.IT_CYBERSECURITY_STAFF]: [
    { resource: RESOURCES.SECURITY_INCIDENTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.ARCHIVE] },
    { resource: RESOURCES.SECURITY_VULNERABILITIES, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.ARCHIVE] },
    { resource: RESOURCES.SECURITY_THREATS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.ARCHIVE] },
    { resource: RESOURCES.SECURITY_RISKS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE] },
    { resource: RESOURCES.CYBERSECURITY_ASSETS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.ARCHIVE] },
    { resource: RESOURCES.DEPARTMENT_ASSETS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE] },
    { resource: RESOURCES.EXTERNAL_SYSTEMS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.SLA_AGREEMENTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE] },
    { resource: RESOURCES.KNOWLEDGE_BASE, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE] },
    { resource: RESOURCES.DOCUMENTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE] },
    { resource: RESOURCES.DATA_CATALOG, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.DATABASE_CONNECTIONS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.DASHBOARD, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.NOTIFICATIONS, actions: [ACTIONS.VIEW, ACTIONS.UPDATE] },
  ],

  // ==================== Digital Transformation Manager - مدير إدارة التحول الرقمي ====================
  // FIX #2: كتالوج البيانات عرض فقط | FIX #13: الأنظمة الخارجية عرض فقط
  [USER_ROLES.IT_DIGITAL_MANAGER]: [
    { resource: RESOURCES.DIGITAL_INITIATIVES, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.DIGITAL_APPLICATIONS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.CLOUD_SERVICES, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.DIGITAL_ASSETS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.DATA_AGREEMENTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.DEPARTMENT_ASSETS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE] },
    { resource: RESOURCES.EXTERNAL_SYSTEMS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.SLA_AGREEMENTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE] },
    { resource: RESOURCES.KNOWLEDGE_BASE, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE] },
    { resource: RESOURCES.DOCUMENTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE] },
    { resource: RESOURCES.DATA_CATALOG, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.DATABASE_CONNECTIONS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.IT_KPIS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE] },
    { resource: RESOURCES.IT_PROJECTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE] },
    { resource: RESOURCES.IT_TICKETS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE] },
    { resource: RESOURCES.DASHBOARD, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.NOTIFICATIONS, actions: [ACTIONS.VIEW, ACTIONS.UPDATE] },
  ],

  // ==================== Digital Transformation Staff - موظف التحول الرقمي ====================
  // FIX #2: كتالوج البيانات عرض فقط | FIX #13: الأنظمة الخارجية عرض فقط
  [USER_ROLES.IT_DIGITAL_STAFF]: [
    { resource: RESOURCES.DIGITAL_INITIATIVES, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.ARCHIVE] },
    { resource: RESOURCES.DIGITAL_APPLICATIONS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.ARCHIVE] },
    { resource: RESOURCES.CLOUD_SERVICES, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.ARCHIVE] },
    { resource: RESOURCES.DIGITAL_ASSETS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.ARCHIVE] },
    { resource: RESOURCES.DATA_AGREEMENTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.ARCHIVE] },
    { resource: RESOURCES.DEPARTMENT_ASSETS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE] },
    { resource: RESOURCES.EXTERNAL_SYSTEMS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.SLA_AGREEMENTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE] },
    { resource: RESOURCES.KNOWLEDGE_BASE, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE] },
    { resource: RESOURCES.DOCUMENTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE] },
    { resource: RESOURCES.DATA_CATALOG, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.DATABASE_CONNECTIONS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.IT_KPIS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE] },
    { resource: RESOURCES.IT_PROJECTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE] },
    { resource: RESOURCES.IT_TICKETS, actions: [ACTIONS.VIEW, ACTIONS.CREATE] },
    { resource: RESOURCES.DASHBOARD, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.NOTIFICATIONS, actions: [ACTIONS.VIEW, ACTIONS.UPDATE] },
  ],

  // ==================== Technical Support Manager - مدير إدارة الدعم الفني ====================
  // FIX #2: كتالوج البيانات عرض فقط | FIX #13: الأنظمة الخارجية عرض فقط
  [USER_ROLES.IT_SUPPORT_MANAGER]: [
    { resource: RESOURCES.SUPPORT_TICKETS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.SUPPORT_ASSETS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.DEPARTMENT_ASSETS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE] },
    { resource: RESOURCES.EXTERNAL_SYSTEMS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.SLA_AGREEMENTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE] },
    { resource: RESOURCES.KNOWLEDGE_BASE, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE] },
    { resource: RESOURCES.DOCUMENTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE] },
    { resource: RESOURCES.DATA_CATALOG, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.DATABASE_CONNECTIONS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.DASHBOARD, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.NOTIFICATIONS, actions: [ACTIONS.VIEW, ACTIONS.UPDATE] },
  ],

  // ==================== Technical Support Staff - موظف الدعم الفني ====================
  // FIX #2: كتالوج البيانات عرض فقط | FIX #13: الأنظمة الخارجية عرض فقط
  [USER_ROLES.IT_SUPPORT_STAFF]: [
    { resource: RESOURCES.SUPPORT_TICKETS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE] },
    { resource: RESOURCES.SUPPORT_ASSETS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE] },
    { resource: RESOURCES.DEPARTMENT_ASSETS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE] },
    { resource: RESOURCES.EXTERNAL_SYSTEMS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.SLA_AGREEMENTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE] },
    { resource: RESOURCES.KNOWLEDGE_BASE, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE] },
    { resource: RESOURCES.DOCUMENTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE] },
    { resource: RESOURCES.DATA_CATALOG, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.DATABASE_CONNECTIONS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.DASHBOARD, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.NOTIFICATIONS, actions: [ACTIONS.VIEW, ACTIONS.UPDATE] },
  ],

  // ==================== DMO Manager - مدير مكتب إدارة البيانات ====================
  // FIX #3: أزيلت security_risks (مسؤولية الأمن السيبراني حصرياً) | FIX #13: الأنظمة الخارجية عرض فقط
  [USER_ROLES.DMO_MANAGER]: [
    { resource: RESOURCES.DATA_CATALOG, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.DATA_AGREEMENTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.DATA_ASSETS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.DATA_FLOWS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.DATABASE_CONNECTIONS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.DMO_REQUESTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.APPROVE] },
    { resource: RESOURCES.DMO_DOCUMENTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.KNOWLEDGE_BASE, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE] },
    { resource: RESOURCES.DOCUMENTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE] },
    { resource: RESOURCES.AUDIT_LOGS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.DASHBOARD, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.NOTIFICATIONS, actions: [ACTIONS.VIEW, ACTIONS.UPDATE] },
    { resource: RESOURCES.COMPLIANCE, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.PDPL_CONSENTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE] },
    { resource: RESOURCES.PDPL_BREACHES, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE] },
    { resource: RESOURCES.PDPL_ROPA, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE] },
    { resource: RESOURCES.NDMO_ASSESSMENTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.APPROVE] },
    { resource: RESOURCES.DATA_CLASSIFICATIONS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.APPROVE] },
    { resource: RESOURCES.PRIVACY_NOTICES, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.APPROVE] },
    { resource: RESOURCES.EXTERNAL_SYSTEMS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.IT_KPIS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE] },
    { resource: RESOURCES.IT_TICKETS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE] },
    { resource: RESOURCES.IT_REFERRALS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE] },
    { resource: RESOURCES.IT_PROJECTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE] },
    { resource: RESOURCES.IT_ASSETS, actions: [ACTIONS.VIEW] },
  ],

  // ==================== DMO Staff - موظف مكتب إدارة البيانات ====================
  // FIX #3: أزيلت security_risks | FIX #13: الأنظمة الخارجية عرض فقط
  [USER_ROLES.DMO_STAFF]: [
    { resource: RESOURCES.DATA_CATALOG, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.ARCHIVE] },
    { resource: RESOURCES.DATA_AGREEMENTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.ARCHIVE] },
    { resource: RESOURCES.DATA_ASSETS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.ARCHIVE] },
    { resource: RESOURCES.DATA_FLOWS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.ARCHIVE] },
    { resource: RESOURCES.DATABASE_CONNECTIONS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.ARCHIVE] },
    { resource: RESOURCES.EXTERNAL_SYSTEMS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.DMO_REQUESTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE] },
    { resource: RESOURCES.DMO_DOCUMENTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.ARCHIVE] },
    { resource: RESOURCES.KNOWLEDGE_BASE, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE] },
    { resource: RESOURCES.DOCUMENTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE] },
    { resource: RESOURCES.DASHBOARD, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.NOTIFICATIONS, actions: [ACTIONS.VIEW, ACTIONS.UPDATE] },
    { resource: RESOURCES.COMPLIANCE, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.ARCHIVE] },
    { resource: RESOURCES.PDPL_CONSENTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE] },
    { resource: RESOURCES.PDPL_BREACHES, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE] },
    { resource: RESOURCES.PDPL_ROPA, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.ARCHIVE] },
    { resource: RESOURCES.NDMO_ASSESSMENTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.ARCHIVE] },
    { resource: RESOURCES.DATA_CLASSIFICATIONS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.ARCHIVE] },
    { resource: RESOURCES.PRIVACY_NOTICES, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE] },
  ],

  // ==================== Data Steward - أمين البيانات ====================
  [USER_ROLES.DATA_STEWARD]: [
    { resource: RESOURCES.DATA_CATALOG, actions: [ACTIONS.VIEW, ACTIONS.UPDATE] },
    { resource: RESOURCES.DATA_ASSETS, actions: [ACTIONS.VIEW, ACTIONS.UPDATE] },
    { resource: RESOURCES.DATA_FLOWS, actions: [ACTIONS.VIEW, ACTIONS.UPDATE] },
    { resource: RESOURCES.DMO_REQUESTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE] },
    { resource: RESOURCES.DASHBOARD, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.NOTIFICATIONS, actions: [ACTIONS.VIEW, ACTIONS.UPDATE] },
  ],

  // ==================== Data Representative - ممثل البيانات ====================
  [USER_ROLES.DATA_REPRESENTATIVE]: [
    { resource: RESOURCES.DATA_CATALOG, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.DATA_ASSETS, actions: [ACTIONS.VIEW, ACTIONS.UPDATE] },
    { resource: RESOURCES.DMO_REQUESTS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE] },
    { resource: RESOURCES.DASHBOARD, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.NOTIFICATIONS, actions: [ACTIONS.VIEW, ACTIONS.UPDATE] },
    { resource: RESOURCES.COMPLIANCE, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.DATA_QUALITY, actions: [ACTIONS.VIEW, ACTIONS.CREATE] },
    { resource: RESOURCES.DATA_CLASSIFICATIONS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.DATA_DICTIONARY, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.DATA_FLOWS, actions: [ACTIONS.VIEW] },
  ],

  // ==================== Committee Chairman - رئيس اللجنة ====================
  // FIX #5: أزيل DELETE على القرارات (القرارات سجل دائم — تُلغى بقرار جديد لا تُحذف)
  [USER_ROLES.COMMITTEE_CHAIRMAN]: [
    { resource: RESOURCES.COMMITTEE_DECISIONS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.APPROVE] },
    { resource: RESOURCES.COMMITTEE_MEETINGS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.COMMITTEE_VOTING, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.MANAGE] },
    { resource: RESOURCES.COMMITTEE_MEMBERS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE] },
    { resource: RESOURCES.COMMITTEE_MINUTES, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.APPROVE] },
    { resource: RESOURCES.COMMITTEE_TASKS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.APPROVE] },
    { resource: RESOURCES.COMMITTEE_SETTINGS, actions: [ACTIONS.VIEW, ACTIONS.UPDATE, ACTIONS.MANAGE] },
    { resource: RESOURCES.DASHBOARD, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.NOTIFICATIONS, actions: [ACTIONS.VIEW, ACTIONS.UPDATE] },
  ],

  // ==================== Committee Vice Chairman - نائب رئيس اللجنة ====================
  // FIX #5: أزيل DELETE على القرارات
  [USER_ROLES.COMMITTEE_VICE_CHAIRMAN]: [
    { resource: RESOURCES.COMMITTEE_DECISIONS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.APPROVE] },
    { resource: RESOURCES.COMMITTEE_MEETINGS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.MANAGE] },
    { resource: RESOURCES.COMMITTEE_VOTING, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE] },
    { resource: RESOURCES.COMMITTEE_MEMBERS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE] },
    { resource: RESOURCES.COMMITTEE_MINUTES, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.APPROVE] },
    { resource: RESOURCES.COMMITTEE_TASKS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.APPROVE] },
    { resource: RESOURCES.COMMITTEE_SETTINGS, actions: [ACTIONS.VIEW, ACTIONS.UPDATE] },
    { resource: RESOURCES.DASHBOARD, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.NOTIFICATIONS, actions: [ACTIONS.VIEW, ACTIONS.UPDATE] },
  ],

  // ==================== Committee Rapporteur - مقرر اللجنة ====================
  // FIX #11: أزيل CREATE على التصويت (فقط الرئيس أو نائبه يبدأ التصويت)
  [USER_ROLES.COMMITTEE_RAPPORTEUR]: [
    { resource: RESOURCES.COMMITTEE_DECISIONS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE] },
    { resource: RESOURCES.COMMITTEE_MEETINGS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE] },
    { resource: RESOURCES.COMMITTEE_VOTING, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.COMMITTEE_MEMBERS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.COMMITTEE_MINUTES, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE] },
    { resource: RESOURCES.COMMITTEE_TASKS, actions: [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.UPDATE] },
    { resource: RESOURCES.COMMITTEE_SETTINGS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.DASHBOARD, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.NOTIFICATIONS, actions: [ACTIONS.VIEW, ACTIONS.UPDATE] },
  ],

  // ==================== Committee Member - عضو اللجنة ====================
  [USER_ROLES.COMMITTEE_MEMBER]: [
    { resource: RESOURCES.COMMITTEE_DECISIONS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.COMMITTEE_MEETINGS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.COMMITTEE_VOTING, actions: [ACTIONS.VIEW, ACTIONS.CREATE] },
    { resource: RESOURCES.COMMITTEE_MEMBERS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.COMMITTEE_MINUTES, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.COMMITTEE_TASKS, actions: [ACTIONS.VIEW, ACTIONS.UPDATE] },
    { resource: RESOURCES.COMMITTEE_SETTINGS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.DASHBOARD, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.NOTIFICATIONS, actions: [ACTIONS.VIEW, ACTIONS.UPDATE] },
  ],

  // ==================== Auditor - المدقق ====================
  // FIX #8: دور مدقق مستقل — عرض شامل عبر جميع الموارد + تصدير بدون أي تعديل
  [USER_ROLES.AUDITOR]: [
    { resource: RESOURCES.AUDIT_LOGS, actions: [ACTIONS.VIEW, ACTIONS.EXPORT] },
    { resource: RESOURCES.USERS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.SESSIONS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.SYSTEM_SETTINGS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.BUSINESS_DEPARTMENTS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.SYSTEMS_STATUS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.IT_PROJECTS, actions: [ACTIONS.VIEW, ACTIONS.EXPORT] },
    { resource: RESOURCES.IT_TICKETS, actions: [ACTIONS.VIEW, ACTIONS.EXPORT] },
    { resource: RESOURCES.IT_ESCALATIONS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.IT_ASSETS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.IT_KPIS, actions: [ACTIONS.VIEW, ACTIONS.EXPORT] },
    { resource: RESOURCES.IT_TEAMS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.IT_VENDORS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.EXTERNAL_SYSTEMS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.IT_REFERRALS, actions: [ACTIONS.VIEW, ACTIONS.EXPORT] },
    { resource: RESOURCES.SLA_AGREEMENTS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.INFRASTRUCTURE_SERVERS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.INFRASTRUCTURE_NETWORK, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.INFRASTRUCTURE_STORAGE, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.INFRASTRUCTURE_MONITORING, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.SECURITY_INCIDENTS, actions: [ACTIONS.VIEW, ACTIONS.EXPORT] },
    { resource: RESOURCES.SECURITY_VULNERABILITIES, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.SECURITY_THREATS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.SECURITY_RISKS, actions: [ACTIONS.VIEW, ACTIONS.EXPORT] },
    { resource: RESOURCES.CYBERSECURITY_ASSETS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.DIGITAL_INITIATIVES, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.DIGITAL_APPLICATIONS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.CLOUD_SERVICES, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.DIGITAL_ASSETS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.SUPPORT_TICKETS, actions: [ACTIONS.VIEW, ACTIONS.EXPORT] },
    { resource: RESOURCES.SUPPORT_ASSETS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.DATA_CATALOG, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.DATA_ASSETS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.DATA_FLOWS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.DATABASE_CONNECTIONS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.DMO_REQUESTS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.DMO_DOCUMENTS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.COMPLIANCE, actions: [ACTIONS.VIEW, ACTIONS.EXPORT] },
    { resource: RESOURCES.PDPL_CONSENTS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.PDPL_BREACHES, actions: [ACTIONS.VIEW, ACTIONS.EXPORT] },
    { resource: RESOURCES.PDPL_ROPA, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.NDMO_ASSESSMENTS, actions: [ACTIONS.VIEW, ACTIONS.EXPORT] },
    { resource: RESOURCES.DATA_CLASSIFICATIONS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.PRIVACY_NOTICES, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.COMMITTEE_DECISIONS, actions: [ACTIONS.VIEW, ACTIONS.EXPORT] },
    { resource: RESOURCES.COMMITTEE_MEETINGS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.COMMITTEE_VOTING, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.COMMITTEE_MEMBERS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.COMMITTEE_MINUTES, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.COMMITTEE_TASKS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.KNOWLEDGE_BASE, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.DOCUMENTS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.DEPARTMENT_ASSETS, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.DASHBOARD, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.NOTIFICATIONS, actions: [ACTIONS.VIEW, ACTIONS.UPDATE] },
  ],

  // ==================== Employee - موظف ====================
  // FIX #9: أضيفت قاعدة المعرفة (عرض فقط — للبحث عن حلول قبل فتح تذكرة)
  [USER_ROLES.EMPLOYEE]: [
    { resource: RESOURCES.SUPPORT_TICKETS, actions: [ACTIONS.VIEW, ACTIONS.CREATE] },
    { resource: RESOURCES.KNOWLEDGE_BASE, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.DASHBOARD, actions: [ACTIONS.VIEW] },
    { resource: RESOURCES.NOTIFICATIONS, actions: [ACTIONS.VIEW, ACTIONS.UPDATE] },
  ],
};

// ==================== Helper Functions ====================

/**
 * Check if a role has permission for a specific action on a resource
 * التحقق من صلاحية دور معين لإجراء عملية على مورد
 */
export function hasPermission(role: string, resource: Resource, action: Action): boolean {
  const normalizedRole = role === 'admin' ? USER_ROLES.SYSTEM_ADMIN : role;
  const permissions = ROLE_PERMISSIONS[normalizedRole];
  if (!permissions) return false;
  
  const resourcePermission = permissions.find(p => p.resource === resource);
  if (!resourcePermission) return false;
  
  return resourcePermission.actions.includes(action);
}

/**
 * Get all permissions for a role
 * الحصول على جميع صلاحيات دور معين
 */
export function getRolePermissions(role: string): Permission[] {
  const normalizedRole = role === 'admin' ? USER_ROLES.SYSTEM_ADMIN : role;
  return ROLE_PERMISSIONS[normalizedRole] || [];
}

/**
 * Get all allowed resources for a role
 * الحصول على جميع الموارد المسموحة لدور معين
 */
export function getAllowedResources(role: string): Resource[] {
  const normalizedRole = role === 'admin' ? USER_ROLES.SYSTEM_ADMIN : role;
  const permissions = ROLE_PERMISSIONS[normalizedRole];
  if (!permissions) return [];
  return permissions.map(p => p.resource);
}

/**
 * Get allowed actions for a role on a specific resource
 * الحصول على العمليات المسموحة لدور معين على مورد محدد
 */
export function getAllowedActions(role: string, resource: Resource): Action[] {
  const normalizedRole = role === 'admin' ? USER_ROLES.SYSTEM_ADMIN : role;
  const permissions = ROLE_PERMISSIONS[normalizedRole];
  if (!permissions) return [];
  
  const resourcePermission = permissions.find(p => p.resource === resource);
  if (!resourcePermission) return [];
  
  return resourcePermission.actions;
}

/**
 * Check if role can view a resource
 */
export function canView(role: string, resource: Resource): boolean {
  return hasPermission(role, resource, ACTIONS.VIEW);
}

/**
 * Check if role can create a resource
 */
export function canCreate(role: string, resource: Resource): boolean {
  return hasPermission(role, resource, ACTIONS.CREATE);
}

/**
 * Check if role can update a resource
 */
export function canUpdate(role: string, resource: Resource): boolean {
  return hasPermission(role, resource, ACTIONS.UPDATE);
}

/**
 * Check if role can delete a resource
 */
export function canDelete(role: string, resource: Resource): boolean {
  return hasPermission(role, resource, ACTIONS.DELETE);
}

/**
 * Check if role can approve a resource
 */
export function canApprove(role: string, resource: Resource): boolean {
  return hasPermission(role, resource, ACTIONS.APPROVE);
}

/**
 * Check if role can manage a resource (full control)
 */
export function canManage(role: string, resource: Resource): boolean {
  return hasPermission(role, resource, ACTIONS.MANAGE);
}

/**
 * Check if role can archive (soft-delete) a resource
 */
export function canArchive(role: string, resource: Resource): boolean {
  return hasPermission(role, resource, ACTIONS.ARCHIVE);
}

// ==================== Navigation Permissions ====================
// تحديد الصفحات المسموحة لكل بوابة

export interface NavPermission {
  path: string;
  resource: Resource;
  minAction: Action;
}

export const PORTAL_NAV_PERMISSIONS: Record<string, NavPermission[]> = {
  [USER_PORTALS.ADMIN]: [
    { path: '/admin', resource: RESOURCES.DASHBOARD, minAction: ACTIONS.VIEW },
    { path: '/admin/users', resource: RESOURCES.USERS, minAction: ACTIONS.VIEW },
    { path: '/admin/departments', resource: RESOURCES.BUSINESS_DEPARTMENTS, minAction: ACTIONS.VIEW },
    { path: '/admin/audit', resource: RESOURCES.AUDIT_LOGS, minAction: ACTIONS.VIEW },
    { path: '/admin/sessions', resource: RESOURCES.SESSIONS, minAction: ACTIONS.VIEW },
    { path: '/admin/systems-status', resource: RESOURCES.SYSTEMS_STATUS, minAction: ACTIONS.VIEW },
  ],
  
  [USER_PORTALS.IT_DIRECTOR]: [
    { path: '/it-director', resource: RESOURCES.DASHBOARD, minAction: ACTIONS.VIEW },
    { path: '/it-director/projects', resource: RESOURCES.IT_PROJECTS, minAction: ACTIONS.VIEW },
    { path: '/it-director/tickets', resource: RESOURCES.IT_TICKETS, minAction: ACTIONS.VIEW },
    { path: '/it-director/escalations', resource: RESOURCES.IT_ESCALATIONS, minAction: ACTIONS.VIEW },
    { path: '/it-director/referrals', resource: RESOURCES.IT_REFERRALS, minAction: ACTIONS.VIEW },
    { path: '/it-director/assets', resource: RESOURCES.IT_ASSETS, minAction: ACTIONS.VIEW },
    { path: '/it-director/kpis', resource: RESOURCES.IT_KPIS, minAction: ACTIONS.VIEW },
    { path: '/it-director/teams', resource: RESOURCES.IT_TEAMS, minAction: ACTIONS.VIEW },
    { path: '/it-director/vendors', resource: RESOURCES.IT_VENDORS, minAction: ACTIONS.VIEW },
    { path: '/it-director/external-systems', resource: RESOURCES.EXTERNAL_SYSTEMS, minAction: ACTIONS.VIEW },
    { path: '/it-director/system-approvals', resource: RESOURCES.SYSTEM_APPROVALS, minAction: ACTIONS.VIEW },
  ],
  
  [USER_PORTALS.IT_DEPARTMENT]: [
    { path: '/department/infrastructure', resource: RESOURCES.DASHBOARD, minAction: ACTIONS.VIEW },
    { path: '/department/infrastructure/servers', resource: RESOURCES.INFRASTRUCTURE_SERVERS, minAction: ACTIONS.VIEW },
    { path: '/department/infrastructure/network', resource: RESOURCES.INFRASTRUCTURE_NETWORK, minAction: ACTIONS.VIEW },
    { path: '/department/infrastructure/storage', resource: RESOURCES.INFRASTRUCTURE_STORAGE, minAction: ACTIONS.VIEW },
    { path: '/department/infrastructure/monitoring', resource: RESOURCES.INFRASTRUCTURE_MONITORING, minAction: ACTIONS.VIEW },
    { path: '/department/infrastructure/tasks', resource: RESOURCES.INFRASTRUCTURE_TASKS, minAction: ACTIONS.VIEW },
    { path: '/department/infrastructure/projects', resource: RESOURCES.INFRASTRUCTURE_PROJECTS, minAction: ACTIONS.VIEW },
    { path: '/department/infrastructure/assets', resource: RESOURCES.DEPARTMENT_ASSETS, minAction: ACTIONS.VIEW },
    { path: '/department/infrastructure/sla', resource: RESOURCES.SLA_AGREEMENTS, minAction: ACTIONS.VIEW },
    { path: '/department/infrastructure/knowledge-base', resource: RESOURCES.KNOWLEDGE_BASE, minAction: ACTIONS.VIEW },
  ],
  
  [USER_PORTALS.CYBERSECURITY]: [
    { path: '/department/cybersecurity', resource: RESOURCES.DASHBOARD, minAction: ACTIONS.VIEW },
    { path: '/department/cybersecurity/incidents', resource: RESOURCES.SECURITY_INCIDENTS, minAction: ACTIONS.VIEW },
    { path: '/department/cybersecurity/vulnerabilities', resource: RESOURCES.SECURITY_VULNERABILITIES, minAction: ACTIONS.VIEW },
    { path: '/department/cybersecurity/threats', resource: RESOURCES.SECURITY_THREATS, minAction: ACTIONS.VIEW },
    { path: '/department/cybersecurity/assets', resource: RESOURCES.DEPARTMENT_ASSETS, minAction: ACTIONS.VIEW },
    { path: '/department/cybersecurity/sla', resource: RESOURCES.SLA_AGREEMENTS, minAction: ACTIONS.VIEW },
    { path: '/department/cybersecurity/knowledge-base', resource: RESOURCES.KNOWLEDGE_BASE, minAction: ACTIONS.VIEW },
  ],

  // بوابة البنية التحتية (المستقلة)
  infrastructure: [
    { path: '/department/infrastructure', resource: RESOURCES.DASHBOARD, minAction: ACTIONS.VIEW },
    { path: '/department/infrastructure/servers', resource: RESOURCES.INFRASTRUCTURE_SERVERS, minAction: ACTIONS.VIEW },
    { path: '/department/infrastructure/network', resource: RESOURCES.INFRASTRUCTURE_NETWORK, minAction: ACTIONS.VIEW },
    { path: '/department/infrastructure/storage', resource: RESOURCES.INFRASTRUCTURE_STORAGE, minAction: ACTIONS.VIEW },
    { path: '/department/infrastructure/monitoring', resource: RESOURCES.INFRASTRUCTURE_MONITORING, minAction: ACTIONS.VIEW },
    { path: '/department/infrastructure/tasks', resource: RESOURCES.INFRASTRUCTURE_TASKS, minAction: ACTIONS.VIEW },
    { path: '/department/infrastructure/projects', resource: RESOURCES.INFRASTRUCTURE_PROJECTS, minAction: ACTIONS.VIEW },
    { path: '/department/infrastructure/assets', resource: RESOURCES.DEPARTMENT_ASSETS, minAction: ACTIONS.VIEW },
    { path: '/department/infrastructure/sla', resource: RESOURCES.SLA_AGREEMENTS, minAction: ACTIONS.VIEW },
    { path: '/department/infrastructure/knowledge-base', resource: RESOURCES.KNOWLEDGE_BASE, minAction: ACTIONS.VIEW },
  ],

  // بوابة التحول الرقمي (المستقلة)
  digital_transformation: [
    { path: '/department/digital-transformation', resource: RESOURCES.DASHBOARD, minAction: ACTIONS.VIEW },
    { path: '/department/digital-transformation/initiatives', resource: RESOURCES.DIGITAL_INITIATIVES, minAction: ACTIONS.VIEW },
    { path: '/department/digital-transformation/applications', resource: RESOURCES.DIGITAL_APPLICATIONS, minAction: ACTIONS.VIEW },
    { path: '/department/digital-transformation/cloud', resource: RESOURCES.CLOUD_SERVICES, minAction: ACTIONS.VIEW },
    { path: '/department/digital-transformation/assets', resource: RESOURCES.DEPARTMENT_ASSETS, minAction: ACTIONS.VIEW },
    { path: '/department/digital-transformation/sla', resource: RESOURCES.SLA_AGREEMENTS, minAction: ACTIONS.VIEW },
    { path: '/department/digital-transformation/knowledge-base', resource: RESOURCES.KNOWLEDGE_BASE, minAction: ACTIONS.VIEW },
  ],

  // بوابة الدعم الفني (المستقلة)
  support: [
    { path: '/department/support', resource: RESOURCES.DASHBOARD, minAction: ACTIONS.VIEW },
    { path: '/department/support/tickets', resource: RESOURCES.SUPPORT_TICKETS, minAction: ACTIONS.VIEW },
    { path: '/department/support/assets', resource: RESOURCES.SUPPORT_ASSETS, minAction: ACTIONS.VIEW },
    { path: '/department/support/sla', resource: RESOURCES.SLA_AGREEMENTS, minAction: ACTIONS.VIEW },
    { path: '/department/support/knowledge-base', resource: RESOURCES.KNOWLEDGE_BASE, minAction: ACTIONS.VIEW },
  ],
  
  [USER_PORTALS.DMO]: [
    { path: '/dmo', resource: RESOURCES.DASHBOARD, minAction: ACTIONS.VIEW },
    { path: '/dmo/data-catalog', resource: RESOURCES.DATA_CATALOG, minAction: ACTIONS.VIEW },
    { path: '/dmo/knowledge-base', resource: RESOURCES.KNOWLEDGE_BASE, minAction: ACTIONS.VIEW },
    { path: '/dmo/documents', resource: RESOURCES.DOCUMENTS, minAction: ACTIONS.VIEW },
  ],
  
  [USER_PORTALS.COMMITTEE]: [
    { path: '/committee', resource: RESOURCES.DASHBOARD, minAction: ACTIONS.VIEW },
    { path: '/committee/decisions', resource: RESOURCES.COMMITTEE_DECISIONS, minAction: ACTIONS.VIEW },
    { path: '/committee/meetings', resource: RESOURCES.COMMITTEE_MEETINGS, minAction: ACTIONS.VIEW },
    { path: '/committee/voting', resource: RESOURCES.COMMITTEE_VOTING, minAction: ACTIONS.VIEW },
    { path: '/committee/members', resource: RESOURCES.COMMITTEE_MEMBERS, minAction: ACTIONS.VIEW },
    { path: '/committee/minutes', resource: RESOURCES.COMMITTEE_MINUTES, minAction: ACTIONS.VIEW },
    { path: '/committee/tasks', resource: RESOURCES.COMMITTEE_TASKS, minAction: ACTIONS.VIEW },
    { path: '/committee/settings', resource: RESOURCES.COMMITTEE_SETTINGS, minAction: ACTIONS.VIEW },
  ],
  
  [USER_PORTALS.DATA_REP]: [
    { path: '/data-representative', resource: RESOURCES.DASHBOARD, minAction: ACTIONS.VIEW },
    { path: '/dmo/data-catalog', resource: RESOURCES.DATA_CATALOG, minAction: ACTIONS.VIEW },
    { path: '/dmo/data-assets', resource: RESOURCES.DATA_ASSETS, minAction: ACTIONS.VIEW },
    { path: '/dmo/data-dictionary', resource: RESOURCES.DATA_DICTIONARY, minAction: ACTIONS.VIEW },
    { path: '/dmo/data-classifications', resource: RESOURCES.DATA_CLASSIFICATIONS, minAction: ACTIONS.VIEW },
    { path: '/dmo/data-quality', resource: RESOURCES.DATA_QUALITY, minAction: ACTIONS.VIEW },
    { path: '/dmo/governance-requests', resource: RESOURCES.DMO_REQUESTS, minAction: ACTIONS.VIEW },
    { path: '/dmo/steward-requests', resource: RESOURCES.DMO_REQUESTS, minAction: ACTIONS.VIEW },
    { path: '/dmo/regulatory-compliance', resource: RESOURCES.COMPLIANCE, minAction: ACTIONS.VIEW },
    { path: '/dmo/compliance-monitoring', resource: RESOURCES.COMPLIANCE, minAction: ACTIONS.VIEW },
    { path: '/dmo/notifications', resource: RESOURCES.NOTIFICATIONS, minAction: ACTIONS.VIEW },
  ],
  
  [USER_PORTALS.STEWARD]: [
    { path: '/steward', resource: RESOURCES.DASHBOARD, minAction: ACTIONS.VIEW },
  ],
  
  [USER_PORTALS.AUDITOR]: [
    { path: '/auditor', resource: RESOURCES.DASHBOARD, minAction: ACTIONS.VIEW },
    { path: '/auditor/audit-logs', resource: RESOURCES.AUDIT_LOGS, minAction: ACTIONS.VIEW },
    { path: '/auditor/tickets', resource: RESOURCES.IT_TICKETS, minAction: ACTIONS.VIEW },
    { path: '/auditor/projects', resource: RESOURCES.IT_PROJECTS, minAction: ACTIONS.VIEW },
    { path: '/auditor/compliance', resource: RESOURCES.COMPLIANCE, minAction: ACTIONS.VIEW },
    { path: '/auditor/security', resource: RESOURCES.SECURITY_INCIDENTS, minAction: ACTIONS.VIEW },
    { path: '/auditor/committees', resource: RESOURCES.COMMITTEE_DECISIONS, minAction: ACTIONS.VIEW },
  ],

  [USER_PORTALS.EMPLOYEE]: [
    { path: '/employee', resource: RESOURCES.DASHBOARD, minAction: ACTIONS.VIEW },
  ],
};

/**
 * Check if user can access a specific path
 * التحقق من إمكانية وصول المستخدم لمسار معين
 */
export function canAccessPath(role: string, portal: string, path: string): boolean {
  const navPermissions = PORTAL_NAV_PERMISSIONS[portal];
  if (!navPermissions) return false;
  
  const navPermission = navPermissions.find(p => path.startsWith(p.path));
  if (!navPermission) return false;
  
  return hasPermission(role, navPermission.resource, navPermission.minAction);
}

/**
 * Get allowed navigation items for a user
 * الحصول على عناصر التنقل المسموحة للمستخدم
 */
export function getAllowedNavItems(role: string, portal: string): string[] {
  const navPermissions = PORTAL_NAV_PERMISSIONS[portal];
  if (!navPermissions) return [];
  
  return navPermissions
    .filter(p => hasPermission(role, p.resource, p.minAction))
    .map(p => p.path);
}
